name: C++ Test Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up OpenSSL libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev  # Install OpenSSL development package
      if: startsWith(matrix.config.runner, 'ubuntu-')

    - name: Install gtest
      run: |
        sudo apt-get update
        sudo apt-get install libgtest-dev


    - name: Build and run C++ test
      working-directory: cpp
      run: |
        make
        ./test_edes